version: "3.9"

services:
  books:
    build:
      context: .
      dockerfile: src/BooksShowcase.Api/Dockerfile
      target: final
    ports:
      - "5134:5134"
    env_file:
      - .env
    environment:
      CassandraOptions__Addresses__0: ${CASSANDRA_ADDRESS_0}
      CassandraOptions__Keyspace: ${CASSANDRA_KEYSPACE}
    depends_on:
      - cassandra_migrations
      - kibana
      - logstash
  
  cassandra:
    image: cassandra
    env_file:
      - config/cassandra/cassandra.env
    ports:
      - "7199:7199" # JMX
      - "7000:7000" # cluster communication
      - "7001:7001" # cluster communication (SSL)
      - "9042:9042" # native protocol clients
      - "9160:9160" # thrift clients
    volumes:
      - ./data/cassandra:/var/lib/cassandra
  
  cassandra_migrations:
    image: yuranye/cassandra_migrations:0.0.1
    command: migrate -h ${CASSANDRA_ADDRESS_0} -k ${CASSANDRA_KEYSPACE} -s scripts --port 9042 --force_keyspace
    volumes:
      - ./build/cassandra/migrations/:/app/scripts
    depends_on:
      - cassandra
  
  logstash:
    image: logstash:7.17.5
    volumes:
      - ./config/logstash/pipeline:/usr/share/logstash/pipeline
      - ./config/logstash/settings:/usr/share/logstash/config
    ports:
      - "8080:8080"
    command: logstash -f /usr/share/logstash/pipeline/pipeline.conf
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    depends_on:
      - elastic

  elastic:
    image: elasticsearch:7.17.5
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      ELASTIC_USER: ${ELASTIC_USER}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      xpack.license.self_generated.type: ${ELK_LICENSE}
    volumes:
      - elastic_state:/usr/share/elasticsearch/data:rw
  
  kibana:
    image: kibana:7.17.5
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_HOSTS: "http://elastic:9200"
    depends_on:
      - elastic
      

volumes:
  elastic_state: { }