version: "3.9"

services:
  books:
    build:
      context: .
      dockerfile: src/BooksShowcase.Api/Dockerfile
      target: final
    ports:
      - "5080:5080"
    env_file:
      - .env
    environment:
      CassandraOptions__Addresses__0: ${CASSANDRA_ADDRESS_0}
      CassandraOptions__Keyspace: ${CASSANDRA_KEYSPACE}
    depends_on:
      - cassandra_migrations
  
  cassandra:
    image: cassandra
    env_file:
      - config/cassandra/cassandra.env
    ports:
      - "7199:7199" # JMX
      - "7000:7000" # cluster communication
      - "7001:7001" # cluster communication (SSL)
      - "9042:9042" # native protocol clients
      - "9160:9160" # thrift clients
    volumes:
      - ./data/cassandra:/var/lib/cassandra
  
  cassandra_migrations:
    image: yuranye/cassandra_migrations:0.0.1
    command: migrate -h ${CASSANDRA_ADDRESS_0} -k ${CASSANDRA_KEYSPACE} -s scripts --port 9042 --force_keyspace
    volumes:
      - ./build/cassandra/migrations/:/app/scripts
    depends_on:
      - cassandra
  
  elastic:
    image: elasticsearch